chore(deps): version update
sourcefuse/loopback4-s3 pull request #215
Opened 2024-12-13 06:15 UTC by Tyagi-Sunny

## Description
loopback version update

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-13 14:31 UTC, yeshamavani requested changes
<img width="913" alt="image" src="https://github.com/user-attachments/assets/16c419fd-f3ac-49de-a94d-675258c32e1e" />

Also include changes of remaining Prs in this

2024-12-13 14:31 UTC, yeshamavani commented on package.json
> +    "@types/node": "^16.18.119",
why is the version downgraded

2024-12-17 14:09 UTC, Tyagi-Sunny commented on package.json
> +    "@types/node": "^16.18.119",
done

2024-12-18 06:55 UTC, yeshamavani approved these changes

2024-12-18 06:56 UTC, merged

2024-12-18 06:57 UTC, yeshamavani commented
:tada: This PR is included in version 9.0.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-s3/v/9.0.3)
- [GitHub release](https://github.com/sourcefuse/loopback4-s3/releases/tag/v9.0.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: