updated aws library
sourcefuse/loopback4-s3 pull request #4
Opened 2020-12-24 14:12 UTC by sf-kansara

Updated s3 library.

References:
https://github.com/aws/aws-sdk-js-v3
https://github.com/aws/aws-sdk-js-v3#configuration
https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/

2020-12-24 14:44 UTC, samarpan-b requested changes

2020-12-24 14:44 UTC, samarpan-b commented on src/providers/aws-s3.provider.ts
> -    AWS.config.update(Object.assign({}, {signatureVersion: 'v4'}, this.config));
This is needed. we need to define signatureversion

2021-03-23 08:53 UTC, SouravSF commented
@sf-kansara Can you confirm if this works on local????

2021-05-17 11:33 UTC, akshatdubeysf commented
@ashutosh-bansal-2136

2021-07-06 13:00 UTC, w20k commented
Don't you need to add `region` to `AWSS3Bindings.Config`? Or I'm missing something and change docs, also :)

2021-07-08 11:53 UTC, ashutosh-bansal-2136 commented
Hi @w20k,
This PR is stale actually, if u have any other issues then u can tell us at [this](https://github.com/sourcefuse/loopback4-s3/pull/12).

2022-05-09 07:10 UTC, akshatdubeysf commented
Closing this as it has been fixed in another PR

2022-05-09 07:10 UTC, closed without merging